# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    if: ${{ github.repository_owner == 'Lepinoid' && !contains(github.event.head_commit.message, '[CI-SKIP]')}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.github_token }}
          prefix: ${{ github.ref }}

      - name: Publish
        uses: uTen2c/publish-to-github@v1
        with:
          repo: ${{ secrets.REPO }}
          token-user: ${{ secrets.TOKEN_USER }}
          token: ${{ secrets.TOKEN }}
          commit-user-name: ${{ secrets.PUBLISH_COMMIT_USER_NAME }}
          commit-user-email: ${{ secrets.PUBLISH_COMMIT_USER_EMAIL }}